language: python

python:
  - 3.8

addons:
  ssh_known_hosts: 161.35.99.229

branches:
  only:
  - master

before_install:
  - openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv -in .travis/travis_rsa.enc -out ~/.ssh/travis_rsa -d
  - chmod 600 ~/.ssh/travis_rsa

install:
        - pip3 install pipenv
        - pip3 install boto3
        - pip3 install flask
        - pip3 install pytest
script:
        -
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    all_branches: true
