language: python
python:
  - 3.8

install:
        - pip3 install pipenv
        - pip3 install boto3
        - pip3 install flask
        - pip3 install pytest

script: pytest


branches:
  only:
    - master
