language: python

python:
  - 3.8

addons:
  ssh_known_hosts: 64.227.18.245
  
install:
        - pip3 install pipenv
        - pip3 install boto3
        - pip3 install flask
        - pip3 install pytest

before_deploy:
- openssl aes-256-cbc -K $encrypted_137f45644142_key -iv $encrypted_137f45644142_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    branch: deploy
