language: python

python:
  - 3.8

addons:
  ssh_known_hosts: 161.35.99.229

branches:
  only:
  - master

before_install:
  - openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv -in travis_rsa.enc -out /tmp/travis_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/travis_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
        - pip3 install pipenv
        - pip3 install boto3
        - pip3 install flask
        - pip3 install pytest
script:
        -
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    all_branches: true
